# `cargo-deny` configuration.

feature-depth = 1

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "warn"
severity-threshold = "Medium"
ignore = [
  # Marvin attack fot the `rsa` crate (there's no fix yet)
  "RUSTSEC-2023-0071",
]

[licenses]
unlicensed = "deny"
allow = [
  # Permissive open-source licenses
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip = [
  # Old version used by `yew-macro`
  { name = "syn", version = "^1" },
  # Old version used by `yew` via `gloo-worker` and `proc-macro-crate`
  { name = "toml_edit", version = "^0.19" },
]
skip-tree = [
  # Old version used by `yew` via `prokio` together with the new version
  { name = "gloo", version = "^0.8" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
