# `cargo-deny` configuration.

feature-depth = 1

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "warn"
severity-threshold = "Medium"

[licenses]
unlicensed = "deny"
allow = [
  # Permissive open-source licenses
  "MIT",
  "Apache-2.0",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip = [
  # Old version used by `yew-macro`
  { name = "syn", version = "^1" },
]
skip-tree = [
  # Old version used by `yew` (via `implicit-clone`); no fix is available ATM
  { name = "indexmap", version = "^1.9" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
