[build]
publish = "dist/"
command = "bash ./build.sh"

[build.environment]
NODE_VERSION = "20.11.0"
# `--force` flag is required because of pug@3 conflicting with pug-loader peer dependency.
# pug@3 works fine in practice.
NPM_FLAGS = "--force"
RUST_VERSION = "1.75.0"

# Set up redirects from aux domains to the canonical one.
[[redirects]]
from = "https://justwebtoken.dev/*"
to = "https://justwebtoken.io/:splat"
status = 301
force = true
