# Standard JWT headers.
[standard_headers.jku]
name = "Key set URL"
link = "https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.2"
description = """\
URL of the <a href="https://www.rfc-editor.org/rfc/rfc7517.html#section-5">JSON Web Key Set</a> \
containing the key that has signed the token.\
"""

[standard_headers.kid]
name = "Key ID"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.4"
description = "Identifier of the key that has signed the token."

[standard_headers.x5u]
name = "Key certificate"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.5"
description = "URL of the X.509 certificate for the signing key."

[standard_headers."x5t#S256"]
name = "Key certificate thumbprint"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.8"
description = "SHA-256 thumbprint of the X.509 certificate for the signing key."

[standard_headers.typ]
name = "Type"
link = "https://tools.ietf.org/html/rfc7519#section-5.1"
description = "Application-specific token type. Usually set to <code>JWT</code>."

# Standard claims together with their descriptions.
[standard_claims.exp]
name = "Expiration timestamp"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4"
description = """\
Earliest timestamp after which the token must be \
rejected as expired. Use of this claim is recommended in order to \
minimize impact of signing key being compromised.\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.iat]
name = "Issuance timestamp"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6"
description = """\
Timestamp at which token was issued. Useful to determine \
the token age and for debugging purposes.\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.nbf]
name = "Maturity timestamp"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5"
description = """\
“Not before” timestamp restricting the minimum clock time \
required to accept the token (i.e., opposite of the exp claim).\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.iss]
name = "Issuer"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1"
description = """\
Principal that has issued this token. Apps \
may use the claim to decide whether the issuer is trustworthy.\
"""
format = "Application-specific; generally, a string (potentially, a URI)"

[standard_claims.sub]
name = "Subject"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2"
description = """\
Describes entity that the claims apply to, generally by using its ID \
which is globally unique or unique to the issuing system. \
In the context of OAuth 2.0, the subject is the end user.\
"""
format = """\
Application-specific; generally, a string identifier (e.g., a \
<a href="https://datatracker.ietf.org/doc/html/rfc4122">UUID</a>)\
"""

[standard_claims.aud]
name = "Audience"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3"
description = """\
Identifies intended recipient(s) of the token. The token verifier must \
identify with a value in this claim; otherwise, token verification must fail.\
"""
format = "Array of strings (potentially, URIs), or a single string in case of a single allowed recipient"

[standard_claims.jti]
name = "Token ID"
category = "basic"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7"
description = """\
Unique token identifier chosen using a collision-resistant algorithm \
(e.g., pseudo-randomly with sufficient entropy). Primarily useful \
to prevent <a href="https://en.wikipedia.org/wiki/Replay_attack">replay attacks</a>;
with this claim, produced tokens are guaranteed to be unqiue.
"""
format = """\
Application-specific; generally, represents random bytes (e.g., in form of a \
<a href="https://datatracker.ietf.org/doc/html/rfc4122">UUID</a>)\
"""

[standard_claims.name]
name = "Full name"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = """\
Full name of the end user this token is issued to, potentially inlcuding titles and affixes \
if appropriate.\
"""
format = """\
Human-readable string, such as <code>Dr. John William Doe</code>, with the name components \
separated by a space char\
"""

[standard_claims.given_name]
name = "Given name"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Given name(s) of the user this token is issued to."
format = "String with given names separated by a space char, such as <code>John William</code>"

[standard_claims.family_name]
name = "Family name"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Last name(s) of the user this token is issued to."
format = "String with last names separated by a space char, such as <code>Ortega y Gasset</code>"

[standard_claims.middle_name]
name = "Middle name"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Middle name(s) of the user this token is issued to."
format = "String with middle names separated by a space char, such as <code>Ivanovich</code>"

[standard_claims.nickname]
name = "Nickname"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = """\
Casual name of the user this token is issued to. Semantically similar \
to the <code>given_name</code> claim.\
"""
format = "String such as <code>Mike</code>"

[standard_claims.preferred_username]
name = "Nickname"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = """\
Name identifying the user for the <a href="https://datatracker.ietf.org/doc/html/rfc6749">OAuth 2.0</a> client. \
This is usually a unique human-readable identifier of the user, but the verifier \
must not rely on this claim being unique.\
"""
format = "String such as <code>j.doe</code> or <code>john.doe@example.com</code>"

[standard_claims.profile]
name = "Profile"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Link to the user’s profile page hosted by the issuer"
format = "URL string such as <code>https://example.com/u/john.doe</code>"

[standard_claims.picture]
name = "Picture"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Link to the user’s profile picture or photo hosted by the issuer"
format = """\
URL string such as <code>https://cdn.example.com/pics/127545457835.png</code>. \
The URL must link to an image resource (e.g., a JPEG or PNG), rather than to an HTML page \
containing the image.\
"""

[standard_claims.website]
name = "Website"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Link to the user’s website, such as a blog"
format = "URL string such as <code>https://john-doe.example.com/</code>"

[standard_claims.email]
name = "Email"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s preferred email address"
format = "Email string, for example <code>john.doe@example.com</code>"

[standard_claims.email_verified]
name = "Email verified?"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = """\
Information on whether the issuer has verified the user’s email address \
provided in the <code>email</code> claim.\
"""
format = "Boolean value such as <code>true</code>"

[standard_claims.birthdate]
name = "Birthday"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s date of birth"
format = """\
<a href="https://en.wikipedia.org/wiki/ISO_8601">ISO 8601</a> date, such as <code>1990-04-01</code>. \
Specifying just a year (<code>1990</code>) is admissible as well.\
"""

[standard_claims.zoneinfo]
name = "Time zone"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s preferred time zone"
format = """\
String time zone identifier from the <a href="https://www.iana.org/time-zones">IANA time zone database</a>, \
such as <code>Europe/Paris</code>\
"""

[standard_claims.locale]
name = "Locale"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s preferred locale"
format = """\
String with a <a href="https://datatracker.ietf.org/doc/html/rfc5646">BCP 47</a> language tag, such as \
<code>en-US</code> or <code>fr_CA</code>. \
Both dash <code>-</code> and underscore <code>_</code> separators between the language and \
country codes are allowed.\
"""

[standard_claims.phone_number]
name = "Phone number"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s preferred phone number"
format = """\
String with the phone number. The OpenID Connect spec recommends using \
the <a href="https://www.itu.int/rec/T-REC-E.164-201011-I/en">E.164</a> number format,
such as <code>+1 (425) 555-1212</code>.
"""

[standard_claims.phone_number_verified]
name = "Phone number verified?"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = """\
Information on whether the issuer has verified the user’s phone number \
provided in the <code>phone_number</code> claim.\
"""
format = "Boolean value such as <code>true</code>"

[standard_claims.address]
name = "Address"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "User’s preferred postal address"
format = """\
Object with a subset of the following fields:
<ul class="my-1">
  <li><code>formatted</code> – Full mailing address</li>
  <li><code>street_address</code> – Part of the address related to the street, \
    e.g. house number, street name, PO box</li>
  <li><code>locality</code> – City / locality</li>
  <li><code>region</code> – State, province, region etc.</li>
  <li><code>postal_code</code> – Zip code / postal code</li>
  <li><code>country</code> – Country name</li>
</ul>
<code>formatted</code> and <code>street_address</code> fields can contain newlines, \
which can be represented as <code>\\r\\n</code> or <code>\\n</code> chars.\
"""

[standard_claims.updated_at]
name = "Updated at"
category = "openid_connect"
link = "https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims"
description = "Timestamp when the user’s info was last updated"
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.auth_time]
name = "Authentication time"
category = "authentication"
link = "https://openid.net/specs/openid-connect-core-1_0.html#IDToken"
description = "Timestamp when the user authenticated with the issuer"
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.nonce]
name = "Cryptographic nonce"
category = "authentication"
link = "https://openid.net/specs/openid-connect-core-1_0.html#IDToken"
description = """\
Unique value included into the token to prevent \
<a href="https://en.wikipedia.org/wiki/Replay_attack">replay attacks</a>. \
Similar to the <code>jti</code> claim, but can be specified by the authentication request \
when used within the OAuth 2.0 framework.\
"""
format = """\
Application-specific; generally, represents random bytes (e.g., in form of a \
<a href="https://datatracker.ietf.org/doc/html/rfc4122">UUID</a>)\
"""

[standard_claims.acr]
name = "Authentication context"
category = "authentication"
link = "https://openid.net/specs/openid-connect-core-1_0.html#IDToken"
description = """\
Reference to the method used to authenticate the user, or the class of this method. \
Classes may be represented by the applicable \
<a href="https://id4d.worldbank.org/guide/levels-assurance-loas">authentication level of assurance</a> \
defined in <a href="https://www.iso.org/standard/45138.html">the ISO/IEC 29115 standard</a>. \
For example, level 2 (substantial) corresponds to multi-factor authentication, \
while level 0 is the least reliable (e.g., via a long-term authentication cookie).\
"""
format = """\
String with a URI or a name from the \
<a href="https://www.iana.org/assignments/loa-profiles/loa-profiles.xhtml">level of assurance profiles registry</a> \
maintained by IANA. Authentication assurance levels from ISO/IEC 29115 can be represented as \
number strings, such as <code>2</code>.\
"""

[standard_claims.amr]
name = "Authenticaton methods"
category = "authentication"
link = "https://openid.net/specs/openid-connect-core-1_0.html#IDToken"
description = """\
References for the method(s) used to authenticate the user. As an example, \
this claim may signal that a password and an OTP scheme were used.\
"""
format = "Array of strings, each of strings being an application-specific method identifier"

[standard_claims.azp]
name = "Authorized party"
category = "authentication"
link = "https://openid.net/specs/openid-connect-core-1_0.html#IDToken"
description = """\
Party to which the token was issued. Fulfils almost the same role as the <code>aud</code> claim \
and is only really necessary if the audience claim has a single value, which is different \
from the authorized party.\
"""
format = "String (potentially a URI) with the OAuth 2.0 client ID of the party"

[standard_claims.act]
name = "Actor"
category = "delegation"
link = "https://www.rfc-editor.org/rfc/rfc8693.html#name-act-actor-claim"
description = """\
Party to whom the subject has delegated authority to act on behalf of them. \
This claim can be used in scenarios such as tech support performing actions \
on behalf of a user.\
"""
format = """\
Object with fields being claims about the actor. Almost always includes the <code>sub</code> claim, \
and may include other claims in order to uniquely identify the actor (e.g., the issuer – <code>iss</code>).\
"""

[standard_claims.may_act]
name = "Authorized actor"
category = "delegation"
description = """\
Information about a party that is authorized to act on behalf of the subject. \
This can be used during <a href="https://www.rfc-editor.org/rfc/rfc8693.html">OAuth 2.0 token exchange</a> \
to determine whether the potential delegatee is valid, and to produce a token \
with the <code>act</code> claim as a result.\
"""
link = "https://www.rfc-editor.org/rfc/rfc8693.html#name-may_act-authorized-actor-cl"
format = """\
Object with fields being claims about the actor. Almost always includes the <code>sub</code> claim, \
and may include other claims in order to uniquely identify the actor (e.g., the issuer – <code>iss</code>).\
"""

[standard_claims.scope]
name = "OAuth 2.0 scopes"
category = "oauth"
link = "https://www.rfc-editor.org/rfc/rfc8693.html#name-scope-scopes-claim"
description = """\
Collection of <a href="https://www.rfc-editor.org/rfc/rfc6749#section-3.3">OAuth 2.0 scopes</a> \
that allow restricting valid uses of the token. As an example, \
scopes can be used to restrict token to specific app(s) or service(s) within the verifier system.\
"""
format = "String consisting of one or more space-separated scopes, such as <code>email user_profile</code>"

[standard_claims.client_id]
name = "OAuth 2.0 client"
category = "oauth"
link = "https://www.rfc-editor.org/rfc/rfc8693.html#name-client_id-client-identifier"
description = "ID of the OAuth 2.0 client that has requested the token"
format = "String with an application-specific format"

# Claims categories.
[claims_categories.basic]
title = "Basic claims"
description = """\
Claims from the original <a href="https://www.rfc-editor.org/rfc/rfc7519.html">JWT RFC</a> document.\
"""

[claims_categories.openid_connect]
title = "OpenID Connect claims"
description = """\
Claims related to the idenitity of the token subject defined \
by the <a href="https://openid.net/specs/openid-connect-core-1_0.html">OpenID Connect</a> framework.\
"""

[claims_categories.authentication]
title = "Authentication claims"
description = """\
Claims describing authentication undertaken by the subject in order to create an ID token \
within the <a href="https://openid.net/specs/openid-connect-core-1_0.html">OpenID Connect</a> framework.\
"""

[claims_categories.delegation]
title = "Delegation claims"
description = """\
Claims related to authorization delegation as specified in \
the <a href="https://www.rfc-editor.org/rfc/rfc8693.html">OAuth 2.0 token exchange</a> framework.\
"""

[claims_categories.oauth]
title = "OAuth 2.0 claims"
description = """\
Claims applicable to tokens issued within miltiple \
<a href="https://www.rfc-editor.org/rfc/rfc6749.html">OAuth 2.0</a> flows.\
"""

[claims_categories.unknown]
title = "Unknown claims"
description = "Claims that are application-specific or not yet supported by the website"
