# Standard JWT headers.
[standard_headers.jku]
name = "Key set URL"
link = "https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.2"
description = """\
URL of the <a href="https://www.rfc-editor.org/rfc/rfc7517.html#section-5">JSON Web Key Set</a> \
containing the key that has signed the token.\
"""

[standard_headers.kid]
name = "Key ID"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.4"
description = "Identifier of the key that has signed the token."

[standard_headers.x5u]
name = "Key certificate"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.5"
description = "URL of the X.509 certificate for the signing key."

[standard_headers."x5t#S256"]
name = "Key certificate thumbprint"
link = "https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.8"
description = "SHA-256 thumbprint of the X.509 certificate for the signing key."

[standard_headers.typ]
name = "Type"
link = "https://tools.ietf.org/html/rfc7519#section-5.1"
description = "Application-specific token type. Usually set to <code>JWT</code>."

# Standard claims together with their descriptions.
[standard_claims.exp]
name = "Expiration timestamp"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4"
description = """\
Earliest timestamp after which the token must be \
rejected as expired. Use of this claim is recommended in order to \
minimize impact of signing key being compromised.\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.iat]
name = "Issuance timestamp"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.6"
description = """\
Timestamp at which token was issued. Useful to determine \
the token age and for debugging purposes.\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.nbf]
name = "Maturity timestamp"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.5"
description = """\
“Not before” timestamp restricting the minimum clock time \
required to accept the token (i.e., opposite of the exp claim).\
"""
format = "Unix timestamp – an integer number of seconds since 1970-01-01 00:00:00 in the UTC timezone"

[standard_claims.iss]
name = "Issuer"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1"
description = """\
Principal that has issued this token. Apps \
may use the claim to decide whether the issuer is trustworthy.\
"""
format = "Application-specific; generally, a string (potentially, a URI)"

[standard_claims.sub]
name = "Subject"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2"
description = """\
Describes entity that the claims apply to, generally by using its ID \
which is globally unique or unique to the issuing system.\
"""
format = """\
Application-specific; generally, a string identifier (e.g., a \
<a href="https://datatracker.ietf.org/doc/html/rfc4122">UUID</a>)\
"""

[standard_claims.aud]
name = "Audience"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3"
description = """\
Identifies intended recipient(s) of the token. The token verifier must \
identify with a value in this claim; otherwise, token verification must fail.\
"""
format = "Array of strings (potentially, URIs), or a single string in case of a single allowed recipient"

[standard_claims.jti]
name = "Token ID"
link = "https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.7"
description = """\
Unique token identifier chosen using a collision-resistant algorithm \
(e.g., pseudo-randomly with sufficient entropy). Primarily useful \
to prevent <a href="https://en.wikipedia.org/wiki/Replay_attack">replay attacks</a>;
with this claim, produced tokens are guaranteed to be unqiue.
"""
format = """\
Application-specific; generally, represents random bytes (e.g., in form of a \
<a href="https://datatracker.ietf.org/doc/html/rfc4122">UUID</a>)\
"""
